version: '3'
services:
  app:
    container_name: native-macsilicon-graal-aeroport-batch
    image: artifactory.io/k8s-test/namespace/com.xtremealex/aeroport-batch:native-macsilicon-graal-aeroport

    build:
      context: ..
      dockerfile: docker/native.macSilicon-noBuild.Dockerfile
    ports:
      - "8080:8080"
